---
environment:
  matrix:
    - CYG_ARCH: x86_64
      CYG_ROOT: C:/cygwin64

install:
  - set PATH=C:\cygwin64\bin;%PATH%
  - '%CYG_ROOT%\setup-%CYG_ARCH%.exe -qnNdO -R %CYG_ROOT%
    -l %CYG_ROOT%/var/cache/setup
    -P autoconf
    -P automake
    -P bison
    -P curl
    -P gcc-core
    -P gcc-g++
    -P gettext
    -P gettext-devel
    -P git
    -P intltool
    -P libgmp-devel
    -P libiconv
    -P libncurses-devel
    -P libreadline-devel
    -P libtool
    -P make
    -P mingw-binutils
    -P mingw-gcc-core
    -P mingw-gcc-g++
    -P mingw-pthreads
    -P mingw-runtime
    -P mingw-w32api
    -P pkg-config
    -P wget'

before_build:
  - gcc -v
  - g++ -v

build_script:
  # https://help.appveyor.com/discussions/problems/5170-progresspreference-not-works-always-shown-preparing-modules-for-first-use-in-stderr
  - ps: $ProgressPreference = "SilentlyContinue"
  - bash -lc "
    cd $APPVEYOR_BUILD_FOLDER ;
    echo '==> Running aclocal'     ; aclocal &&
    echo '==> Running autoconf'    ; autoconf &&
    echo '==> Running ./bootstrap' ; ./bootstrap &&
    echo '==> Running ./configure' ; ./configure &&
    echo '==> Running make'        ; make"

test_script:
  # https://help.appveyor.com/discussions/problems/5170-progresspreference-not-works-always-shown-preparing-modules-for-first-use-in-stderr
  - ps: $ProgressPreference = "SilentlyContinue"
  - bash -lc "
    cd $APPVEYOR_BUILD_FOLDER ;
    echo '==> Running make check' ; make check"
